-- Create seats table
CREATE TABLE seats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    seat       VARCHAR(255) NOT NULL,
    show_id    BIGINT NOT NULL,
    hall_id    BIGINT NOT NULL,
    status     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (id),
    CONSTRAINT fk_seats_show_times FOREIGN KEY (show_id) REFERENCES show_times (id),
    CONSTRAINT fk_seats_halls FOREIGN KEY (hall_id) REFERENCES halls (id)
);

CREATE INDEX idx_seats_show_id ON seats (show_id);
CREATE INDEX idx_seats_hall_id ON seats (hall_id);
