
    create table genres (
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table halls (
        capacity integer not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        code varchar(255) not null unique,
        name varchar(255) not null,
        type varchar(255) not null check (type in ('STANDARD','IMAX','VIP')),
        primary key (id)
    );

    create table movie_genres (
        genre_id bigint not null,
        movie_id bigint not null
    );

    create table movies (
        rating float(53),
        release_year integer not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        duration bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        description varchar(255),
        poster_image varchar(255),
        title varchar(255) not null,
        trailer_url varchar(255),
        primary key (id)
    );

    create table reservation_seats (
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        reservation_id bigint not null,
        seat_id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    create table reservations (
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        show_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        primary key (id)
    );

    create table seats (
        created_at timestamp(6),
        deleted_at timestamp(6),
        hall_id bigint not null,
        id bigint generated by default as identity,
        show_id bigint not null,
        updated_at timestamp(6),
        seat varchar(255) not null,
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','DAMAGED')),
        primary key (id)
    );

    create table show_times (
        end_time time(6) not null,
        price numeric(38,2) not null,
        show_date date not null,
        start_time time(6) not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        hall_id bigint not null,
        id bigint generated by default as identity,
        movie_id bigint not null,
        updated_at timestamp(6),
        day varchar(255) not null check (day in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
        status varchar(255) not null check (status in ('SCHEDULED','FULL','FILLING','COMPLETED','CANCELLED')),
        primary key (id)
    );

    create table users (
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        role varchar(255) default 'USER' not null check (role in ('USER','ADMIN')),
        primary key (id)
    );

    alter table if exists movie_genres 
       add constraint FKnfpjuak0xiqpca3gjkwrixiig 
       foreign key (genre_id) 
       references genres;

    alter table if exists movie_genres 
       add constraint FK4ak9svw913jblkfgru84h2phd 
       foreign key (movie_id) 
       references movies;

    alter table if exists reservation_seats 
       add constraint FK755roqq37bto59vxaxis9x3nt 
       foreign key (reservation_id) 
       references reservations;

    alter table if exists reservation_seats 
       add constraint FKo4tbgy4jg06hfaugqx2gxx9we 
       foreign key (seat_id) 
       references seats;

    alter table if exists reservations 
       add constraint FKcubw8fydhk608t81rugxohfj5 
       foreign key (show_id) 
       references show_times;

    alter table if exists reservations 
       add constraint FKb5g9io5h54iwl2inkno50ppln 
       foreign key (user_id) 
       references users;

    alter table if exists seats 
       add constraint FK3jtfe0f60bcpbavj4mctjeasw 
       foreign key (hall_id) 
       references halls;

    alter table if exists seats 
       add constraint FKpll7nkbc1cr8oikmkao5uqq4h 
       foreign key (show_id) 
       references show_times;

    alter table if exists show_times 
       add constraint FKlwdyg27qinr4lfd9h2nlbmd8y 
       foreign key (hall_id) 
       references halls;

    alter table if exists show_times 
       add constraint FK8j8e0814cfoypjrui0bl745ap 
       foreign key (movie_id) 
       references movies;
