CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    title        VARCHAR(255)                            NOT NULL,
    release_year INTEGER                                 NOT NULL,
    description  VARCHAR(255),
    duration     BIGINT                                  NOT NULL,
    rating       DOUBLE PRECISION,
    poster_image VARCHAR(255),
    CONSTRAINT pk_movies PRIMARY KEY (id)
);