CREATE TABLE genres
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE movie_genres
(
    genre_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL
);

ALTER TABLE movie_genres
    ADD CONSTRAINT fk_movgen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);

ALTER TABLE movie_genres
    ADD CONSTRAINT fk_movgen_on_movie FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE movies
DROP
COLUMN duration;

ALTER TABLE movies
    ADD duration BIGINT NOT NULL;