CREATE TABLE day_time_slots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    day          VARCHAR(255)                            NOT NULL,
    time_slot_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_day_time_slots PRIMARY KEY (id)
);

CREATE TABLE time_slots
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    duration   BIGINT                                  NOT NULL,
    CONSTRAINT pk_time_slots PRIMARY KEY (id)
);

ALTER TABLE day_time_slots
    ADD CONSTRAINT FK_DAY_TIME_SLOTS_ON_TIME_SLOT FOREIGN KEY (time_slot_id) REFERENCES time_slots (id);

ALTER TABLE movies
DROP
COLUMN duration;

ALTER TABLE movies
    ADD duration BIGINT NOT NULL;