CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    email        VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255),
    phone_number VARCHAR(255),
    role         VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE movies
DROP
COLUMN duration;

ALTER TABLE movies
    ADD duration BIGINT NOT NULL;

ALTER TABLE time_slots
DROP
COLUMN duration;

ALTER TABLE time_slots
    ADD duration BIGINT NOT NULL;