CREATE TABLE show_times
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    movie_id   BIGINT                                  NOT NULL,
    slot_id    BIGINT                                  NOT NULL,
    show_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_show_times PRIMARY KEY (id)
);

ALTER TABLE show_times
    ADD CONSTRAINT FK_SHOW_TIMES_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE show_times
    ADD CONSTRAINT FK_SHOW_TIMES_ON_SLOT FOREIGN KEY (slot_id) REFERENCES day_time_slots (id);

ALTER TABLE movies
DROP
COLUMN duration;

ALTER TABLE movies
    ADD duration BIGINT NOT NULL;

ALTER TABLE time_slots
DROP
COLUMN duration;

ALTER TABLE time_slots
    ADD duration BIGINT NOT NULL;