CREATE TABLE reservation_seats
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    reservation_id BIGINT                                  NOT NULL,
    show_id        BIGINT                                  NOT NULL,
    seat_id        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_reservation_seats PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    show_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

ALTER TABLE reservation_seats
    ADD CONSTRAINT uk_show_seat UNIQUE (show_id, seat_id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_SHOW FOREIGN KEY (show_id) REFERENCES show_times (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reservation_seats
    ADD CONSTRAINT FK_RESERVATION_SEATS_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE reservation_seats
    ADD CONSTRAINT FK_RESERVATION_SEATS_ON_SHOW FOREIGN KEY (show_id) REFERENCES show_times (id);

ALTER TABLE movies
DROP
COLUMN duration;

ALTER TABLE movies
    ADD duration BIGINT NOT NULL;

ALTER TABLE time_slots
DROP
COLUMN duration;

ALTER TABLE time_slots
    ADD duration BIGINT NOT NULL;

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE show_times
    ALTER COLUMN status SET NOT NULL;